// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1277.Robot2016.subsystems;

import org.usfirst.frc1277.Robot2016.RobotMap;
import org.usfirst.frc1277.Robot2016.commands.Drive;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import com.ni.vision.NIVision;
import com.ni.vision.NIVision.Image;
import edu.wpi.first.wpilibj.CameraServer;


/**
 *
 */
public class DriveTrain extends Subsystem {
	
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    
    private final Encoder leftEncoder = RobotMap.leftEncoder;
    private final Encoder rightEncoder = RobotMap.rightEncoder;
    
    public final double circumference = Math.PI * 10;
    
	public final int camBack;
	public final int camFront;
	public int curCam;
	public Image frame;
	public CameraServer server;
    
	public DriveTrain() {
		
        camBack = NIVision.IMAQdxOpenCamera("cam0", NIVision.IMAQdxCameraControlMode.CameraControlModeController);
        camFront = NIVision.IMAQdxOpenCamera("cam1", NIVision.IMAQdxCameraControlMode.CameraControlModeController);
        curCam = camFront;
        frame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_RGB, 0);
        server = CameraServer.getInstance();
        server.setQuality(60);
        changeCam(camFront);
	}
	
    public int getRightEncoder() {
    	return rightEncoder.get();
    }
    
    public void resetRightEncoder() {
    	rightEncoder.reset();
    }
    
    public void drive(double move, double rotate) {
    	robotDrive.arcadeDrive(move, rotate);
		SmartDashboard.putNumber("Right Encoder", rightEncoder.get());
		SmartDashboard.putNumber("Left Encoder", leftEncoder.get());
    }
    
    public void initDefaultCommand() {
    	setDefaultCommand(new Drive());
    }
    
	public void changeCam(int newId) {
		
		NIVision.IMAQdxStopAcquisition(curCam);
    	NIVision.IMAQdxConfigureGrab(newId);
    	NIVision.IMAQdxStartAcquisition(newId);
    	curCam = newId;
    }
	
    public void updateCam() {
    	
    	NIVision.IMAQdxGrab(curCam, frame, 1);
        server.setImage(frame);
    }
}

